# Generated by Django 6.0.1 on 2026-03-18 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niceadmin_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='abc',
            new_name='wwww',
        ),
    ]
